// import { Outfit as AccentFont } from 'next/font/google';
import type { Metadata } from 'next';
import { baseFont } from '@/app/fonts';
import { Navbar } from '@/app/(home)/(components)/navbar';
import { cn } from '@/lib/utils';
import '@/app/globals.css';
import { ThemeProvider } from '@/components/theme-provider';

// const accentFont = AccentFont({
//   subsets: ['latin'],
//   display: 'swap',
//   weight: ['400', '700', '800'],
//   variable: '--font-accent',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
      </head>
      <body
        // className={`${baseFont.className} ${accentFont.variable}`}
        className={cn(
          'flex flex-col min-h-screen bg-muted',
          baseFont.className,
          // accentFont.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 border-b z-10 bg-inherit">
            <Navbar />
          </header>
          <main className="flex flex-col flex-grow">{children}</main>
          <footer>
            <div className="container text-center text-xs text-muted-foreground py-4">
              Copyright © 2021 — 2024 Indian Type Foundry. All rights reserved.
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
