import { Licorice as AccentFont } from 'next/font/google';
import type { Metadata } from 'next';
import { baseFont } from '@/app/fonts';
import '@/app/globals.css';

const accentFont = AccentFont({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-fancy',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baseFont.className} ${accentFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
