import type { Metadata } from 'next';
import { baseFont } from '@/app/fonts';
import { Navbar } from '@/app/(site)/(components)/navbar';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
      </head>
      <body className={cn('flex flex-col min-h-screen', baseFont.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 border-b z-10 bg-inherit">
            <Navbar />
          </header>
          <main className="flex flex-col flex-grow">{children}</main>
          <footer>
            <div className="container text-center text-xs text-muted-foreground py-4">
              Copyright © 2021 — 2024 Indian Type Foundry. All rights reserved.
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
